=== cust/manuais/nfse/Joinville/Manual_Upload_NFEM_RPS_DIR/Exemplos/dir_1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.nfem.joinville.sc.gov.br" xmlns="http://www.nfem.joinville.sc.gov.br" elementFormDefault="qualified">
  <xs:element name="lote">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="versao" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1" />
              <xs:maxLength value="5" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="numero" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="1" />
              <xs:maxInclusive value="999999" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="tipo" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:enumeration value="2" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="tomador" maxOccurs="1">
          <xs:complexType>
            <xs:all>
              <xs:element type="cpf_cnpj" name="documento" maxOccurs="1" minOccurs="1"/>
              <xs:element name="razao_social" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1" />
                    <xs:maxLength value="60" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="dir" minOccurs ="1" maxOccurs="999">
          <xs:complexType>
            <xs:all>
              
              <xs:element name="numero" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1" />
                    <xs:maxInclusive value="999999" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="serie" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1" />
                    <xs:maxLength value="5" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="data_emissao" minOccurs ="1" maxOccurs="1" type="xs:date" />
              <xs:element name="prestador" maxOccurs="1" minOccurs="1">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="documento" type="documento" maxOccurs="1" minOccurs="1" />
                    <xs:element name="nome" maxOccurs="1" minOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:minLength value="1" />
                          <xs:maxLength value="60" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="internacional" maxOccurs="1" minOccurs="0" type="xs:boolean" />
                    <xs:element name="cidade" maxOccurs="1" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:minLength value="1" />
                          <xs:maxLength value="60" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="estado" maxOccurs="1" minOccurs="0" >
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="AC" />
                          <xs:enumeration value="AL" />
                          <xs:enumeration value="AM" />
                          <xs:enumeration value="AP" />
                          <xs:enumeration value="BA" />
                          <xs:enumeration value="CE" />
                          <xs:enumeration value="DF" />
                          <xs:enumeration value="ES" />
                          <xs:enumeration value="GO" />
                          <xs:enumeration value="MA" />
                          <xs:enumeration value="MG" />
                          <xs:enumeration value="MS" />
                          <xs:enumeration value="MT" />
                          <xs:enumeration value="PA" />
                          <xs:enumeration value="PB" />
                          <xs:enumeration value="PE" />
                          <xs:enumeration value="PI" />
                          <xs:enumeration value="PR" />
                          <xs:enumeration value="RJ" />
                          <xs:enumeration value="RN" />
                          <xs:enumeration value="RO" />
                          <xs:enumeration value="RR" />
                          <xs:enumeration value="RS" />
                          <xs:enumeration value="SC" />
                          <xs:enumeration value="SE" />
                          <xs:enumeration value="SP" />
                          <xs:enumeration value="TO" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="simples_nacional" maxOccurs="1" minOccurs="0" type="xs:boolean" />
                  </xs:all>
                </xs:complexType>
              </xs:element>

              <xs:element name="valor_total" maxOccurs="1" minOccurs="1" type="valor" />
              <xs:element name="valor_base_calculo" maxOccurs="1" minOccurs="0" type="valor" />
              <xs:element name="servico" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="1.01" />
                    <xs:enumeration value="1.02" />
                    <xs:enumeration value="1.03" />
                    <xs:enumeration value="1.04" />
                    <xs:enumeration value="1.05" />
                    <xs:enumeration value="1.06" />
                    <xs:enumeration value="1.07" />
                    <xs:enumeration value="1.08" />
                    <xs:enumeration value="2.01" />
                    <xs:enumeration value="3.01" />
                    <xs:enumeration value="3.02" />
                    <xs:enumeration value="3.03" />
                    <xs:enumeration value="3.04" />
                    <xs:enumeration value="3.05" />
                    <xs:enumeration value="4.01" />
                    <xs:enumeration value="4.02" />
                    <xs:enumeration value="4.03" />
                    <xs:enumeration value="4.04" />
                    <xs:enumeration value="4.05" />
                    <xs:enumeration value="4.06" />
                    <xs:enumeration value="4.07" />
                    <xs:enumeration value="4.08" />
                    <xs:enumeration value="4.09" />
                    <xs:enumeration value="4.10" />
                    <xs:enumeration value="4.11" />
                    <xs:enumeration value="4.12" />
                    <xs:enumeration value="4.13" />
                    <xs:enumeration value="4.14" />
                    <xs:enumeration value="4.15" />
                    <xs:enumeration value="4.16" />
                    <xs:enumeration value="4.17" />
                    <xs:enumeration value="4.18" />
                    <xs:enumeration value="4.19" />
                    <xs:enumeration value="4.20" />
                    <xs:enumeration value="4.21" />
                    <xs:enumeration value="4.22" />
                    <xs:enumeration value="4.23" />
                    <xs:enumeration value="5.01" />
                    <xs:enumeration value="5.02" />
                    <xs:enumeration value="5.03" />
                    <xs:enumeration value="5.04" />
                    <xs:enumeration value="5.05" />
                    <xs:enumeration value="5.06" />
                    <xs:enumeration value="5.07" />
                    <xs:enumeration value="5.08" />
                    <xs:enumeration value="5.09" />
                    <xs:enumeration value="6.01" />
                    <xs:enumeration value="6.02" />
                    <xs:enumeration value="6.03" />
                    <xs:enumeration value="6.04" />
                    <xs:enumeration value="6.05" />
                    <xs:enumeration value="7.01" />
                    <xs:enumeration value="7.02" />
                    <xs:enumeration value="7.03" />
                    <xs:enumeration value="7.04" />
                    <xs:enumeration value="7.05" />
                    <xs:enumeration value="7.06" />
                    <xs:enumeration value="7.07" />
                    <xs:enumeration value="7.08" />
                    <xs:enumeration value="7.09" />
                    <xs:enumeration value="7.10" />
                    <xs:enumeration value="7.11" />
                    <xs:enumeration value="7.12" />
                    <xs:enumeration value="7.13" />
                    <xs:enumeration value="7.14" />
                    <xs:enumeration value="7.15" />
                    <xs:enumeration value="7.16" />
                    <xs:enumeration value="7.17" />
                    <xs:enumeration value="7.18" />
                    <xs:enumeration value="7.19" />
                    <xs:enumeration value="7.20" />
                    <xs:enumeration value="7.21" />
                    <xs:enumeration value="7.22" />
                    <xs:enumeration value="8.01" />
                    <xs:enumeration value="8.02" />
                    <xs:enumeration value="9.01" />
                    <xs:enumeration value="9.02" />
                    <xs:enumeration value="9.03" />
                    <xs:enumeration value="10.01" />
                    <xs:enumeration value="10.02" />
                    <xs:enumeration value="10.03" />
                    <xs:enumeration value="10.04" />
                    <xs:enumeration value="10.05" />
                    <xs:enumeration value="10.06" />
                    <xs:enumeration value="10.07" />
                    <xs:enumeration value="10.08" />
                    <xs:enumeration value="10.09" />
                    <xs:enumeration value="10.10" />
                    <xs:enumeration value="11.01" />
                    <xs:enumeration value="11.02" />
                    <xs:enumeration value="11.03" />
                    <xs:enumeration value="11.04" />
                    <xs:enumeration value="12.01" />
                    <xs:enumeration value="12.02" />
                    <xs:enumeration value="12.03" />
                    <xs:enumeration value="12.04" />
                    <xs:enumeration value="12.05" />
                    <xs:enumeration value="12.06" />
                    <xs:enumeration value="12.07" />
                    <xs:enumeration value="12.08" />
                    <xs:enumeration value="12.09" />
                    <xs:enumeration value="12.10" />
                    <xs:enumeration value="12.11" />
                    <xs:enumeration value="12.12" />
                    <xs:enumeration value="12.13" />
                    <xs:enumeration value="12.14" />
                    <xs:enumeration value="12.15" />
                    <xs:enumeration value="12.16" />
                    <xs:enumeration value="12.17" />
                    <xs:enumeration value="13.01" />
                    <xs:enumeration value="13.02" />
                    <xs:enumeration value="13.03" />
                    <xs:enumeration value="13.04" />
                    <xs:enumeration value="13.05" />
                    <xs:enumeration value="14.01" />
                    <xs:enumeration value="14.02" />
                    <xs:enumeration value="14.03" />
                    <xs:enumeration value="14.04" />
                    <xs:enumeration value="14.05" />
                    <xs:enumeration value="14.06" />
                    <xs:enumeration value="14.07" />
                    <xs:enumeration value="14.08" />
                    <xs:enumeration value="14.09" />
                    <xs:enumeration value="14.10" />
                    <xs:enumeration value="14.11" />
                    <xs:enumeration value="14.12" />
                    <xs:enumeration value="14.13" />
                    <xs:enumeration value="15.01" />
                    <xs:enumeration value="15.02" />
                    <xs:enumeration value="15.03" />
                    <xs:enumeration value="15.04" />
                    <xs:enumeration value="15.05" />
                    <xs:enumeration value="15.06" />
                    <xs:enumeration value="15.07" />
                    <xs:enumeration value="15.08" />
                    <xs:enumeration value="15.09" />
                    <xs:enumeration value="15.10" />
                    <xs:enumeration value="15.11" />
                    <xs:enumeration value="15.12" />
                    <xs:enumeration value="15.13" />
                    <xs:enumeration value="15.14" />
                    <xs:enumeration value="15.15" />
                    <xs:enumeration value="15.16" />
                    <xs:enumeration value="15.17" />
                    <xs:enumeration value="15.18" />
                    <xs:enumeration value="16.01" />
                    <xs:enumeration value="17.01" />
                    <xs:enumeration value="17.02" />
                    <xs:enumeration value="17.03" />
                    <xs:enumeration value="17.04" />
                    <xs:enumeration value="17.05" />
                    <xs:enumeration value="17.06" />
                    <xs:enumeration value="17.07" />
                    <xs:enumeration value="17.08" />
                    <xs:enumeration value="17.09" />
                    <xs:enumeration value="17.10" />
                    <xs:enumeration value="17.11" />
                    <xs:enumeration value="17.12" />
                    <xs:enumeration value="17.13" />
                    <xs:enumeration value="17.14" />
                    <xs:enumeration value="17.15" />
                    <xs:enumeration value="17.16" />
                    <xs:enumeration value="17.17" />
                    <xs:enumeration value="17.18" />
                    <xs:enumeration value="17.19" />
                    <xs:enumeration value="17.20" />
                    <xs:enumeration value="17.21" />
                    <xs:enumeration value="17.22" />
                    <xs:enumeration value="17.23" />
                    <xs:enumeration value="17.24" />
                    <xs:enumeration value="18.01" />
                    <xs:enumeration value="19.01" />
                    <xs:enumeration value="20.01" />
                    <xs:enumeration value="20.02" />
                    <xs:enumeration value="20.03" />
                    <xs:enumeration value="21.01" />
                    <xs:enumeration value="22.01" />
                    <xs:enumeration value="23.01" />
                    <xs:enumeration value="24.01" />
                    <xs:enumeration value="25.01" />
                    <xs:enumeration value="25.02" />
                    <xs:enumeration value="25.03" />
                    <xs:enumeration value="25.04" />
                    <xs:enumeration value="26.01" />
                    <xs:enumeration value="27.01" />
                    <xs:enumeration value="28.01" />
                    <xs:enumeration value="29.01" />
                    <xs:enumeration value="30.01" />
                    <xs:enumeration value="31.01" />
                    <xs:enumeration value="32.01" />
                    <xs:enumeration value="33.01" />
                    <xs:enumeration value="34.01" />
                    <xs:enumeration value="35.01" />
                    <xs:enumeration value="36.01" />
                    <xs:enumeration value="37.01" />
                    <xs:enumeration value="38.01" />
                    <xs:enumeration value="39.01" />
                    <xs:enumeration value="40.01" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="valor_iss" maxOccurs="1" minOccurs="1" type="valor" />
              <xs:element name="aliquota_iss" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:fractionDigits value="2"/>
                    <xs:minInclusive value="0.01"/>
                    <xs:maxExclusive value="100.00"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- tipos que foram criados -->
  <xs:simpleType name="cpf_cnpj">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{11}||\d{14}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="documento">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w+"/>
      <xs:maxLength value="14" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="valor">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:minInclusive value="0.01"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== cust/manuais/nfse/Joinville/Manual_Upload_NFEM_RPS_DIR/Exemplos/dir_1.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<lote 
xmlns="http://www.nfem.joinville.sc.gov.br"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.nfem.joinville.sc.gov.br dir_1.0.xsd">
  <versao>1.0</versao>
  <numero>2</numero>
  <tipo>2</tipo>
  <tomador>
    <documento>02339928000120</documento>
    <razao_social>Razão Social</razao_social>
  </tomador>

  <dir>
    <numero>1</numero>
    <serie>1</serie>
    <data_emissao>2008-11-01</data_emissao>

    <prestador>
      <documento>11111111111111</documento>
      <nome>Nome Prestador</nome>
      <cidade>Florianópolis</cidade>
      <estado>SC</estado>
    </prestador>

    <valor_total>1000.00</valor_total>
    <valor_base_calculo>100.0</valor_base_calculo>
    <servico>1.01</servico>
    <valor_iss>2.0</valor_iss>
    <aliquota_iss>2.00</aliquota_iss>
  </dir>

  <dir>
    <numero>2</numero>
    <serie>1</serie>
    <data_emissao>2008-11-01</data_emissao>

    <prestador>
      <documento>11111111111</documento>
      <nome>Nome Prestador</nome>
      <cidade>Joinville</cidade>
      <estado>SC</estado>
    </prestador>

    <valor_total>100.00</valor_total>
    <valor_base_calculo>100.00</valor_base_calculo>
    <servico>14.05</servico>
    <valor_iss>5.00</valor_iss>
    <aliquota_iss>5.00</aliquota_iss>
  </dir>
</lote>
